#!/bin/bash

set -e

NOCOLOR='\033[0m'
CYAN='\033[0;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

color()
{
    echo -e "$1$*${NOCOLOR}"
}

color "${LIGHTBLUE}" " ██████╗ █████╗ ██╗      █████╗  ██████╗ ███████╗       ██████╗ ███████╗"
color "${LIGHTBLUE}" "██╔════╝██╔══██╗██║     ██╔══██╗██╔═══██╗██╔════╝      ██╔═══██╗██╔════╝"
color "${LIGHTBLUE}" "██║     ███████║██║     ███████║██║   ██║███████╗█████╗██║   ██║███████╗"
color "${LIGHTBLUE}" "██║     ██╔══██║██║     ██╔══██║██║   ██║╚════██║╚════╝██║   ██║╚════██║"
color "${LIGHTBLUE}" "╚██████╗██║  ██║███████╗██║  ██║╚██████╔╝███████║      ╚██████╔╝███████║"
color "${LIGHTBLUE}" " ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝       ╚═════╝ ╚══════╝"
echo
echo
color "${PURPLE}" "Welcome to Calaos-OS!"
echo
color "${CYAN}" "Calaos-OS is currently initializing. Please wait..."
color "${CYAN}" "This can take a few minutes. Please be patient."
echo
echo

source_files=(/usr/share/calaos/*.source)

for source_file in "${source_files[@]}"; do
    source "$source_file"
    ct_name=$(basename "$source_file" .source)

    load_containers_cache "$ct_name" "${IMAGE_SRC}"
done

echo
color "${GREEN}" "Initialization done!"
echo "Continuing boot..."
echo
sleep 2

# change back to main console
chvt 1
