#!/bin/bash

set -e

fs="/mnt/calaos"
rundir="/run/calaos"

for d in cache \
    haproxy \
    influxdb/data \
    influxdb/config \
    zigbee2mqtt \
    mosquitto/data \
    mosquitto/config \
    grafana/data \
    config \
    ola
do
    mkdir -p ${fs}/${d}
done

mkdir -p $rundir

#Create a unique token
if [ ! -e $rundir/calaos-ct.token ]
then
    echo "$(date +%s-%N)-$RANDOM" > $rundir/calaos-ct.token
fi

if [ -e /.calaos-live ]
then
    touch $rundir/calaos-live
fi

#For OLA we need to store /etc/ola to /mnt
#It saves the ola config on the dedicated /mnt/calaos folder
#This script has to be started once before olad service is started
if [ ! -L /etc/ola ]; then
    rm -fr /etc/ola
    ln -s ${fs}/ola /etc/ola
    chown -R olad:olad /etc/ola ${fs}/ola
fi
