#!/bin/bash

ct_name="$1"

# Get fqdn of image (docker.io|ghcr.io|...)
if [ -f /etc/containers/systemd/"$ct_name".container ]
then
    image=$(< /etc/containers/systemd/"$ct_name".container grep Image= | cut -d= -f 2)
else
    image="$2"
fi

if [ -z "$image" ]
then
    echo "Usage: $0 <containe_name> <full image name>"
    echo "  ex: $0 calaos-home ghcr.io/calaos/calaos_home:latest"
    exit 1
fi

# build container cache directory
cache=/var/lib/cache/containers/${ct_name}.tar

if [ -f "$cache" ]
then
    echo "loading $cache"

    # Podman loads file archive from cache and copy it in the local repository
    podman load < "$cache"

    echo "Image : $image"

    # Remove the cache
    rm -rf "$cache"
fi
