#!/bin/bash

if [ -e /tmp/calaos-os.container.install ]
then
    echo "Not pulling image. Calaos-OS image creation in progress..."
    exit 0
fi

# Check if pkgname parameter is provided
if [ -z "$1" ]; then
    echo "Please provide the pkgname parameter."
    exit 1
fi

pkgname="$1"
url="/usr/share/calaos/$pkgname.source"

# Check if the source file exists
if [ ! -f "$url" ]; then
    echo "Source file $url does not exist."
    exit 1
fi

# Read the URL from the source file
source "$url"

image_base=$(echo "$IMAGE_SRC" | cut -d: -f 1)
image_tag=$(echo "$IMAGE_SRC" | cut -d: -f 2)

echo " > Removing old container image"
for i in $(podman images | grep "$image_base" | awk '{print $3}')
do
    podman rmi "$i"
done

# Clean old remaining container images
echo " > Cleaning old images"
podman image prune -f

echo " > Pulling new image $IMAGE_SRC"
podman pull "$IMAGE_SRC"

# Remove old tags if they exist
if podman image exists "localhost/var/lib/cache/containers/$pkgname"; then
    podman rmi "localhost/var/lib/cache/containers/$pkgname"
fi
