#!/bin/bash

if [ -e /tmp/calaos-os.container.install ]
then
    echo "Not pulling image. Calaos-OS image creation in progress..."
    exit 0
fi

# Check if pkgname parameter is provided
if [ -z "$1" ]; then
    echo "Please provide the pkgname parameter."
    exit 1
fi

pkgname="$1"
url="/usr/share/calaos/$pkgname.source"

# Check if the source file exists
if [ ! -f "$url" ]; then
    echo "Source file $url does not exist."
    exit 1
fi

# Read the URL from the source file
image_url=$(cat "$url")

echo " > Pulling image $image_url"
podman pull "$image_url"

# get image name
image_name=$(echo "$image_url" | cut -d ':' -f 1)

# get version
image_version=$(echo "$image_url" | cut -d ':' -f 2)

#get sha of image from podman
sha=$(podman images -a | grep "$image_name" | grep "$image_version" | awk -F ' ' '{ print $3 }')

# tag latest
podman image tag "$sha" "$image_name":latest

# Clean old remaining container images
echo " > Cleaning old images"
podman image prune -f

# Remove old tags if they exist
if podman image exists "localhost/var/lib/cache/containers/$pkgname"; then
    podman rmi "localhost/var/lib/cache/containers/$pkgname"
fi
