#!/bin/sh
opts=""
case "$*" in
  "registry login"*) opts="-t";;
esac
podman container run $opts --pull=always -i --rm --net host \
  -u "$(id -u):$(id -g)" -e HOME -v $HOME:$HOME \
  ghcr.io/regclient/regctl:latest "$@"