name: Build deb package

on:
  push:

jobs:
  build-and-push-deb-pkg:
    name: Build deb package and push to repositories
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.1.1
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          
      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Increment dev release version
        id: bump_version
        uses: actionsdesk/semver@0.6.0-rc.10
        with:
          prerelease: withBuildNumber
          prelabel: alpha
          initial_version: ${{ steps.fetch-latest-release.outputs.latest-release }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: |
          docker run \
              --rm \
              -v ${{ github.workspace }}:/work \
              -v $(pwd):/${{ github.workspace }} \
              -w ${{ github.workspace }} \
              --platform linux/${{ matrix.arch }} \
              ghcr.io/calaos/debian_deb_build_base \
              /build-deb.sh ${{ steps.bump_version.outputs.release }}
          

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: pkg/*.deb

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.bump_version.outputs.release }}
          token: ${{ secrets.ACTION_DISPATCH }}
  
      - name: Create a Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          tag: ${{ steps.bump_version.outputs.release }}
          name: ${{ steps.bump_version.outputs.release }}
          files: pkg/*.deb
          prerelease: true
          gzip: false

      - name: Update repo cache
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
