name: Build deb package

on:
  push:
    branches: [ main ]

    
jobs:
  build-and-push-deb-pkg:
    name: Build deb package and push to repositories
    runs-on: ubuntu-latest
    steps:
      - id: debug
        run: |
          echo $GITHUB_OUTPUT
          ls -la $GITHUB_OUTPUT

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Build package
        id: build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/calaos/debian_deb_build_base
          options: -v ${{ github.workspace }}:/work  -e "GITHUB_OUTPUT"  -v ${{ env.GITHUB_OUTPUT }}:${{ env.GITHUB_OUTPUT }}
          run: |
            pysemver bump prerelease ${{ steps.fetch-latest-release.outputs.latest-release }}
            export release=$(pysemver bump prerelease ${{ steps.fetch-latest-release.outputs.latest-release }})
            echo "release=$release"
            /work/build-deb.sh $release && echo release=$release >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: pkg/*.deb
  
      - name: Create a Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          tag: ${{ steps.bump_version.build.release }}
          name: ${{ steps.bump_version.build.release }}
          files: pkg/*.deb
          prerelease: true
          allow_override: true
          gzip: false

      - name: Update repo cache
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
