name: Build deb package

on:
  push:
    branches: [ main ]

    
jobs:
  # define job to build and publish docker image
  build-and-push-deb-pkg:
    name: Build deb package and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
  
    # steps to perform in job
    steps:
      - name: Build Debian package
        uses: pi-top/debian-package-build-action@master
        with:
          target_architecture: amd64
          docker_image: debian:bookworm
          build_directory: artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: artifacts/*.deb
