name: Build deb package

on:
  push:
    branches: [ main ]

    
jobs:
  build-and-push-deb-pkg:
    name: Build deb package and push to repositories
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: calaos/debian_deb_build_base
          options: -v ${{ github.workspace }}:/work
          run: |
            /build-deb.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: pkg/*.deb
