name: Release new container image

on:
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Image name'
        required: true
        default: 'haproxy'
        type: choice
        options:
          - haproxy
          - zigbee2mqtt
          - mosquitto
          - influxdb
          - grafana

      rel:
        description: 'Release'
        required: true
        type: boolean

      source:
        description: 'Container image url (docker.io/haproxy:1.2.3)'
        required: true

      version:
        description: 'Container image version (1.2.3)'
        required: true

env:
  CALAOS_REL_URL: https://releases.calaos.fr/v4/image

jobs:
  update-calaos-os-releases:
    name: Update calaos-os-releases
    runs-on: ubuntu-latest

    steps:
      - name: update calaos release
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ env.CALAOS_REL_URL }}${{ (github.event.inputs.rel == 'true' && '') || '-dev' }}/${{ github.event.inputs.imagename }}"
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.CALAOS_REL_TOKEN }}
          data: '{"name": "${{ github.event.inputs.imagename }}", "source": "${{ github.event.inputs.source }}", "version": "${{ github.event.inputs.version }}"}'